version: '3.4'
services:
  # Learning Locker
  learning-locker-api-worker:
    command: ['node', '/opt/learning-locker/worker/dist/server']
    container_name: learning-locker-api-worker
    image: lpgregistry.azurecr.io/lpg-learning-locker:fe8104bf2f0fedb8f5af138bd8860a9c27dd2bb12ecb827f09e754e279a70fa8
    working_dir: /opt/learning-locker

  learning-locker-ui:
    command: ['/opt/learning-locker/run-ui.sh']
    container_name: learning-locker-ui
    image: lpgregistry.azurecr.io/lpg-learning-locker:fe8104bf2f0fedb8f5af138bd8860a9c27dd2bb12ecb827f09e754e279a70fa8
    ports:
      - 3000:3000
    working_dir: /opt/learning-locker

  learning-locker-xapi:
    command: ['node', '/opt/xapi-service/dist/server']
    container_name: learning-locker-xapi
    depends_on:
      - mongodb
      - redis
      - learning-locker-api-worker
    image: lpgregistry.azurecr.io/lpg-learning-locker:fe8104bf2f0fedb8f5af138bd8860a9c27dd2bb12ecb827f09e754e279a70fa8
    ports:
      - 8083:8083
    working_dir: /opt/xapi-service

  setup-learning-locker:
    command:
      [
        '/opt/learning-locker/./node_modules/.bin/babel-node',
        '/opt/learning-locker/mkadmin.js',
      ]
    depends_on:
      - mongodb
    environment:
      - NODE_PATH=/opt/learning-locker
    image: lpgregistry.azurecr.io/lpg-learning-locker:fe8104bf2f0fedb8f5af138bd8860a9c27dd2bb12ecb827f09e754e279a70fa8
    working_dir: /opt/learning-locker
  # /Learning Locker